name: Gatsby Publish

on:
  push:
    branches:
      - src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.0.0
      - name: Add Google Domain Verification file
        run: |
          git fetch origin google-file
          git --work-tree=static checkout google-file -- .
      - name: Build Gatsby site
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
